with open('src/data_processor.py', 'w') as f:
    f.write("import pandas as pd\n")
    f.write("\n")
    f.write("class DataProcessor:\n")
    f.write("\n")
    f.write("    def load(self, filepath):\n")
    f.write("        df = pd.read_csv(filepath)\n")
    f.write("        return self.clean(df)\n")
    f.write("\n")
    f.write("    def clean(self, df):\n")
    f.write("        df.columns = df.columns.str.strip().str.lower()\n")
    f.write("        df['date'] = pd.to_datetime(df['date'], errors='coerce')\n")
    f.write("        df['amount'] = pd.to_numeric(df['amount'], errors='coerce')\n")
    f.write("        df.dropna(subset=['amount', 'description', 'date'], inplace=True)\n")
    f.write("        df['description'] = df['description'].str.strip().str.lower()\n")
    f.write("        df['month'] = df['date'].dt.to_period('M').astype(str)\n")
    f.write("        df['day_of_week'] = df['date'].dt.day_name()\n")
    f.write("        df['week'] = df['date'].dt.isocalendar().week.astype(int)\n")
    f.write("        return df.reset_index(drop=True)\n")

print("File written successfully!")