import os

os.makedirs("src", exist_ok=True)
os.makedirs("models", exist_ok=True)

def write_file(path, lines):
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Written: {path}")

# ── src/__init__.py ──────────────────────────────────────
write_file("src/__init__.py", [""])

# ── src/data_processor.py ────────────────────────────────
write_file("src/data_processor.py", [
    "import pandas as pd",
    "",
    "class DataProcessor:",
    "",
    "    def load(self, filepath):",
    "        df = pd.read_csv(filepath)",
    "        return self.clean(df)",
    "",
    "    def clean(self, df):",
    "        df.columns = df.columns.str.strip().str.lower()",
    "        df['date'] = pd.to_datetime(df['date'], errors='coerce')",
    "        df['amount'] = pd.to_numeric(df['amount'], errors='coerce')",
    "        df.dropna(subset=['amount', 'description', 'date'], inplace=True)",
    "        df['description'] = df['description'].str.strip().str.lower()",
    "        df['month'] = df['date'].dt.to_period('M').astype(str)",
    "        df['day_of_week'] = df['date'].dt.day_name()",
    "        df['week'] = df['date'].dt.isocalendar().week.astype(int)",
    "        return df.reset_index(drop=True)",
])

# ── src/nlp_engine.py ────────────────────────────────────
write_file("src/nlp_engine.py", [
    "import re",
    "import nltk",
    "from nltk.corpus import stopwords",
    "from nltk.stem import PorterStemmer",
    "",
    "nltk.download('stopwords', quiet=True)",
    "nltk.download('punkt', quiet=True)",
    "",
    "class NLPEngine:",
    "",
    "    def __init__(self):",
    "        self.stop_words = set(stopwords.words('english'))",
    "        self.stemmer    = PorterStemmer()",
    "",
    "    def preprocess(self, text):",
    "        text = str(text).lower()",
    "        text = re.sub(r'[^a-z\\s]', '', text)",
    "        tokens = text.split()",
    "        tokens = [t for t in tokens if t not in self.stop_words]",
    "        tokens = [self.stemmer.stem(t) for t in tokens]",
    "        return ' '.join(tokens)",
    "",
    "    def preprocess_series(self, series):",
    "        return series.apply(self.preprocess)",
])

# ── src/ml_classifier.py ─────────────────────────────────
write_file("src/ml_classifier.py", [
    "import os",
    "import joblib",
    "from sklearn.pipeline import Pipeline",
    "from sklearn.feature_extraction.text import TfidfVectorizer",
    "from sklearn.linear_model import LogisticRegression",
    "from sklearn.model_selection import train_test_split",
    "from sklearn.metrics import classification_report, accuracy_score",
    "",
    "class ExpenseClassifier:",
    "",
    "    def __init__(self):",
    "        self.model = Pipeline([",
    "            ('tfidf', TfidfVectorizer(ngram_range=(1,2), max_features=5000)),",
    "            ('clf',   LogisticRegression(max_iter=300, C=1.0, random_state=42)),",
    "        ])",
    "",
    "    def train(self, X, y):",
    "        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)",
    "        self.model.fit(X_train, y_train)",
    "        preds    = self.model.predict(X_test)",
    "        accuracy = accuracy_score(y_test, preds)",
    "        print(f'Model Accuracy: {accuracy * 100:.2f}%')",
    "        print(classification_report(y_test, preds))",
    "        return self",
    "",
    "    def predict(self, X):",
    "        return self.model.predict(X)",
    "",
    "    def save(self, path='models/classifier.pkl'):",
    "        os.makedirs(os.path.dirname(path), exist_ok=True)",
    "        joblib.dump(self.model, path)",
    "        print(f'Model saved to {path}')",
    "",
    "    def load(self, path='models/classifier.pkl'):",
    "        self.model = joblib.load(path)",
    "        print(f'Model loaded from {path}')",
    "        return self",
])

# ── src/predictor.py ─────────────────────────────────────
write_file("src/predictor.py", [
    "import pandas as pd",
    "",
    "class Predictor:",
    "",
    "    def monthly_trend(self, df):",
    "        return df.groupby('month')['amount'].sum().reset_index()",
    "",
    "    def category_split(self, df):",
    "        return df.groupby('category')['amount'].sum().reset_index()",
    "",
    "    def weekly_trend(self, df):",
    "        return df.groupby('week')['amount'].sum().reset_index()",
    "",
    "    def daywise_trend(self, df):",
    "        order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']",
    "        result = df.groupby('day_of_week')['amount'].sum().reindex(order).reset_index()",
    "        return result",
    "",
    "    def savings_analysis(self, df, income=50000):",
    "        total_spent  = df['amount'].sum()",
    "        months       = df['month'].nunique()",
    "        avg_monthly  = total_spent / months if months > 0 else total_spent",
    "        savings_rate = max(0, (income - avg_monthly) / income * 100)",
    "        top_category = df.groupby('category')['amount'].sum().idxmax()",
    "        return {",
    "            'total_spent':    round(total_spent, 2),",
    "            'avg_monthly':    round(avg_monthly, 2),",
    "            'savings_rate_%': round(savings_rate, 1),",
    "            'top_category':   top_category,",
    "            'total_months':   months,",
    "        }",
    "",
    "    def budget_recommendations(self, df):",
    "        cat_totals = df.groupby('category')['amount'].sum()",
    "        total      = cat_totals.sum()",
    "        tips       = []",
    "        for cat, amt in cat_totals.items():",
    "            pct = amt / total * 100",
    "            if pct > 35:",
    "                tips.append(f'Warning: {cat} is {pct:.1f}% of your budget - try to reduce it.')",
    "            elif pct > 25:",
    "                tips.append(f'Note: {cat} is {pct:.1f}% of spending - keep an eye on it.')",
    "        if not tips:",
    "            tips.append('Your spending is well balanced across categories!')",
    "        return tips",
])

# ── src/report_generator.py ──────────────────────────────
write_file("src/report_generator.py", [
    "class ReportGenerator:",
    "",
    "    def monthly_summary(self, df):",
    "        return (",
    "            df.groupby(['month', 'category'])['amount']",
    "            .sum().unstack(fill_value=0).round(2)",
    "        )",
    "",
    "    def top_transactions(self, df, n=10):",
    "        return (",
    "            df.nlargest(n, 'amount')[['date','description','amount','category']]",
    "            .reset_index(drop=True)",
    "        )",
    "",
    "    def generate_text_summary(self, savings_info):",
    "        lines = [",
    "            f\"Total Spent      : Rs {savings_info['total_spent']:,}\",",
    "            f\"Avg Monthly Spend: Rs {savings_info['avg_monthly']:,}\",",
    "            f\"Savings Rate     : {savings_info['savings_rate_%']}%\",",
    "            f\"Biggest Category : {savings_info['top_category']}\",",
    "            f\"Months Analyzed  : {savings_info['total_months']}\",",
    "        ]",
    "        return '\\n'.join(lines)",
])

# ── src/visualizer.py ────────────────────────────────────
write_file("src/visualizer.py", [
    "import plotly.express as px",
    "",
    "class Visualizer:",
    "",
    "    def monthly_bar(self, trend_df):",
    "        return px.bar(trend_df, x='month', y='amount',",
    "                      title='Monthly Total Spending',",
    "                      labels={'amount': 'Amount (Rs)', 'month': 'Month'},",
    "                      color_discrete_sequence=['#636EFA'])",
    "",
    "    def category_pie(self, cat_df):",
    "        return px.pie(cat_df, names='category', values='amount',",
    "                      title='Spending by Category', hole=0.4)",
    "",
    "    def category_bar(self, cat_df):",
    "        return px.bar(cat_df.sort_values('amount'),",
    "                      x='amount', y='category', orientation='h',",
    "                      title='Category-wise Expenditure',",
    "                      labels={'amount': 'Amount (Rs)', 'category': 'Category'},",
    "                      color='amount', color_continuous_scale='Blues')",
    "",
    "    def daily_line(self, df):",
    "        daily = df.groupby('date')['amount'].sum().reset_index()",
    "        return px.line(daily, x='date', y='amount',",
    "                       title='Daily Spending Over Time',",
    "                       labels={'amount': 'Amount (Rs)', 'date': 'Date'})",
    "",
    "    def daywise_bar(self, daywise_df):",
    "        return px.bar(daywise_df, x='day_of_week', y='amount',",
    "                      title='Spending by Day of Week',",
    "                      labels={'amount': 'Amount (Rs)', 'day_of_week': 'Day'},",
    "                      color_discrete_sequence=['#EF553B'])",
])

# ── train_model.py ───────────────────────────────────────
write_file("train_model.py", [
    "import sys",
    "import os",
    "sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))",
    "",
    "from src.data_processor import DataProcessor",
    "from src.nlp_engine     import NLPEngine",
    "from src.ml_classifier  import ExpenseClassifier",
    "",
    "print('Loading data...')",
    "dp = DataProcessor()",
    "df = dp.load('data/sample_data.csv')",
    "print(f'Loaded {len(df)} transactions')",
    "",
    "print('Preprocessing with NLP...')",
    "nlp = NLPEngine()",
    "X   = nlp.preprocess_series(df['description'])",
    "y   = df['category']",
    "",
    "print('Training ML classifier...')",
    "clf = ExpenseClassifier()",
    "clf.train(X, y)",
    "clf.save('models/classifier.pkl')",
    "print('Training complete!')",
])

# ── app.py ───────────────────────────────────────────────
write_file("app.py", [
    "import sys",
    "import os",
    "sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))",
    "",
    "import streamlit as st",
    "import pandas as pd",
    "",
    "from src.data_processor   import DataProcessor",
    "from src.nlp_engine       import NLPEngine",
    "from src.ml_classifier    import ExpenseClassifier",
    "from src.predictor        import Predictor",
    "from src.report_generator import ReportGenerator",
    "from src.visualizer       import Visualizer",
    "",
    "st.set_page_config(page_title='AI Expense Analyzer', layout='wide')",
    "st.title('AI-Powered Expense Analyzer')",
    "st.markdown('Upload your transaction CSV and get instant AI-driven insights.')",
    "",
    "st.sidebar.header('Settings')",
    "uploaded = st.sidebar.file_uploader('Upload Transactions CSV', type=['csv'])",
    "income   = st.sidebar.number_input('Your Monthly Income (Rs)', value=50000, step=1000)",
    "use_ai   = st.sidebar.checkbox('Use AI to auto-classify categories', value=True)",
    "",
    "if uploaded is None:",
    "    st.info('Upload a CSV file from the sidebar to begin.')",
    "    st.markdown('**Expected CSV columns:** date, description, amount')",
    "    st.code('date,description,amount\\n2024-01-05,Swiggy order,320\\n2024-01-06,Ola cab,150')",
    "    st.stop()",
    "",
    "dp = DataProcessor()",
    "df = dp.clean(pd.read_csv(uploaded))",
    "",
    "if use_ai and os.path.exists('models/classifier.pkl'):",
    "    nlp = NLPEngine()",
    "    clf = ExpenseClassifier()",
    "    clf.load('models/classifier.pkl')",
    "    X = nlp.preprocess_series(df['description'])",
    "    df['category'] = clf.predict(X)",
    "    st.sidebar.success('AI classification applied')",
    "elif 'category' not in df.columns:",
    "    st.sidebar.warning('Run train_model.py first to enable AI classification.')",
    "",
    "pred = Predictor()",
    "vis  = Visualizer()",
    "rep  = ReportGenerator()",
    "",
    "savings = pred.savings_analysis(df, income)",
    "tips    = pred.budget_recommendations(df)",
    "",
    "st.subheader('Overview')",
    "c1, c2, c3, c4 = st.columns(4)",
    "c1.metric('Total Spent',       f\"Rs {savings['total_spent']:,}\")",
    "c2.metric('Avg Monthly Spend', f\"Rs {savings['avg_monthly']:,}\")",
    "c3.metric('Savings Rate',      f\"{savings['savings_rate_%']}%\")",
    "c4.metric('Top Category',      savings['top_category'])",
    "",
    "st.markdown('---')",
    "st.subheader('Spending Trends')",
    "col1, col2 = st.columns(2)",
    "col1.plotly_chart(vis.monthly_bar(pred.monthly_trend(df)),   use_container_width=True)",
    "col2.plotly_chart(vis.category_pie(pred.category_split(df)), use_container_width=True)",
    "",
    "col3, col4 = st.columns(2)",
    "col3.plotly_chart(vis.daily_line(df),                        use_container_width=True)",
    "col4.plotly_chart(vis.daywise_bar(pred.daywise_trend(df)),   use_container_width=True)",
    "",
    "st.plotly_chart(vis.category_bar(pred.category_split(df)),   use_container_width=True)",
    "",
    "st.markdown('---')",
    "col5, col6 = st.columns(2)",
    "with col5:",
    "    st.subheader('Financial Summary')",
    "    st.text(rep.generate_text_summary(savings))",
    "with col6:",
    "    st.subheader('Budget Recommendations')",
    "    for tip in tips:",
    "        st.info(tip)",
    "",
    "st.markdown('---')",
    "st.subheader('Detailed Data')",
    "with st.expander('Top 10 Highest Transactions'):",
    "    st.dataframe(rep.top_transactions(df), use_container_width=True)",
    "with st.expander('Monthly Breakdown by Category'):",
    "    st.dataframe(rep.monthly_summary(df), use_container_width=True)",
    "with st.expander('Full Raw Data'):",
    "    st.dataframe(df, use_container_width=True)",
])

print("")
print("All files written successfully!")
print("Next steps:")
print("  1. python train_model.py")
print("  2. streamlit run app.py")